# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(db_index=True, max_length=40, verbose_name='ID объявления')),
                ('price_equation', models.DecimalField(decimal_places=2, default=0.1, max_digits=10, verbose_name='Цена')),
                ('direction', models.CharField(choices=[('buy', 'Обьявление о продаже клиенту'), ('sell', 'Обьявление о покупке у клиента')], max_length=80, verbose_name='Тип обьявления')),
                ('online_provider', models.CharField(max_length=20, verbose_name='Инструмент (QIWI и т.д.)')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('bank_name', models.CharField(max_length=80, verbose_name='Имя банка')),
                ('min_price', models.DecimalField(decimal_places=2, default=0.1, max_digits=10, verbose_name='Минимальная цена')),
                ('max_price', models.DecimalField(decimal_places=2, default=0.1, max_digits=10, verbose_name='Максимальная цена')),
                ('max_amount', models.IntegerField(verbose_name='Максимальный объем')),
                ('account_info', models.TextField(verbose_name='Информация о аккаунте')),
                ('msg', models.TextField(verbose_name='Сообщение')),
                ('price_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Предел цены (lim цена)')),
                ('amount_limit', models.IntegerField(verbose_name='Предел объема (lim V)')),
                ('min_amount_filter', models.IntegerField(verbose_name='V игнор')),
                ('ad_creation_time_filter', models.DateTimeField(verbose_name='T игнор')),
                ('delta_amount_filter', models.IntegerField(verbose_name='Delta V')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона (при работе с QIWI)')),
                ('step', models.IntegerField(verbose_name='Шаг цены')),
                ('steps_quantity', models.IntegerField(verbose_name='Количество шагов')),
                ('ignored_logins', models.TextField(blank=True, verbose_name='Игнорируемые логины')),
                ('invisible_trade_ids', models.TextField(blank=True, verbose_name='ID сделок-невидимок')),
                ('price_rollback', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Откат цены (откат)')),
                ('rollback_time', models.IntegerField(verbose_name='Время отката (T откат) в секундах')),
                ('call_frequency', models.IntegerField(verbose_name='Частота бота в секундах')),
                ('start_msg', models.TextField(blank=True, verbose_name='Сообщение при начале сделки')),
                ('finish_msg', models.TextField(blank=True, verbose_name='Сообщение при завершении сделки')),
                ('is_top_fifteen', models.BooleanField(verbose_name='Топ 15')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Включено ли объявление?')),
                ('is_updated', models.BooleanField(default=False, verbose_name='Обновлять ли объявление?')),
                ('current_amount', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Обьявления',
                'verbose_name': 'Обьявление',
            },
        ),
        migrations.CreateModel(
            name='CurrentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ad_position', models.IntegerField(verbose_name='Текущая позиция')),
                ('current_step', models.IntegerField(verbose_name='Текущий номер шага')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(db_index=True, max_length=40, verbose_name='Логин')),
                ('hmac_key', models.CharField(db_index=True, max_length=140, verbose_name='HMAC ключ')),
                ('hmac_secret', models.CharField(max_length=140, verbose_name='HMAC пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Аккаунты LocalBitcoin',
                'verbose_name': 'Аккаунт LocalBitcoin',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='bot.LocalUser', verbose_name='Пользователь-владелец'),
        ),
    ]
