# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='invisible_logins',
        ),
        migrations.AddField(
            model_name='ad',
            name='invisible_trade_ids',
            field=models.TextField(blank=True, verbose_name='ID сделок-невидимок'),
        ),
    ]
