# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localuser',
            name='ad_id',
        ),
        migrations.AddField(
            model_name='localuser',
            name='login',
            field=models.CharField(db_index=True, default='', max_length=40, verbose_name='Логин'),
        ),
    ]
