# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170512_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentinfo',
            name='ad',
        ),
        migrations.AddField(
            model_name='ad',
            name='current_ad_position',
            field=models.IntegerField(null=True, verbose_name='Текущая позиция'),
        ),
        migrations.AddField(
            model_name='ad',
            name='current_step',
            field=models.IntegerField(null=True, verbose_name='Текущий номер шага'),
        ),
        migrations.DeleteModel(
            name='CurrentInfo',
        ),
    ]
