# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20170513_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='call_frequency',
        ),
    ]
