# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20170604_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='last_update_time',
            new_name='last_online_time',
        ),
    ]
