# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20170604_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_creation_time_filter',
        ),
    ]
